<template>
  <div class="salary-slip-container">
    <div class="header">
      <h1>Salary Slip Generator</h1>
    </div>

    <!-- Month Picker -->
    <div class="form-group">
      <label for="month-select">Select Month:</label>
      <input type="month" v-model="selectedMonth" class="form-control" />
    </div>
    <img src="" alt="">
    <!-- Fetch Salary Button -->
    <button @click="fetchSalaryForMonth" class="btn-fetch-salary" :disabled="!selectedMonth">
      Fetch Salary
    </button>
    <!-- Salary Details Form -->
    <div v-if="showSlip" class="salary-details">
      <button @click="generatePDF" class="btn-download">Download Salary Slip (PDF)</button>
      <div v-if="showSlip" class="salary-slip-preview">
        <h2>Salary Slip Preview</h2>
        <div class="slip-details">
          <p><strong>Working Hours:</strong> {{ employeeDetails.total_working_hours }} hours</p>
          <p><strong>Salary:</strong> ${{ employeeDetails.salary }}</p>
          <p><strong>Status:</strong> {{ employeeDetails.status }}</p>
          <p><strong>Paid Date:</strong> {{ employeeDetails.paid_date }}</p>
          <p><strong>Position:</strong> {{ employeeDetails.employee_position }}</p>
          <p><strong>Department:</strong> {{ employeeDetails.employee_department }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useStore } from 'vuex';
import jsPDF from 'jspdf';

const store = useStore();
const selectedMonth = ref('');
const employeeDetails = ref({
  total_working_hours: '00:00:00',
  salary: 0,
  status: 'unpaid',
  paid_date: '',
  employee_position: '',
  employee_department: ''
});


const showSlip = ref(false);

// Function to fetch salary details for the selected month
const fetchSalaryForMonth = async () => {
  if (selectedMonth.value) {
    const month = selectedMonth.value;
    await store.dispatch('employee/fetchSalaryDetails', month);

    employeeDetails.value = store.getters['employee/employeeSalaryDetails'];
    showSlip.value = true;
  }
};
const generatePDF = async () => {
  showSlip.value = true;

  const doc = new jsPDF({
    unit: 'pt', 
    format: 'a4',
    orientation: 'portrait'
  });

  const marginTop = 60;
  const marginLeft = 40;

  const logoUrl = '../../../src/assets/images/login.jpeg';
  doc.addImage(logoUrl, 'PNG', marginLeft, marginTop - 30, 50, 50);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('MIHRM', doc.internal.pageSize.getWidth() / 2, marginTop, { align: 'center' });
  doc.setFontSize(18);
  doc.text('Salary Slip', doc.internal.pageSize.getWidth() / 2, marginTop + 25, { align: 'center' });
  doc.setDrawColor(100);
  doc.line(marginLeft, marginTop + 35, doc.internal.pageSize.getWidth() - marginLeft, marginTop + 35);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);

  let yPosition = marginTop + 60;

  const details = [
    { label: 'Working Hours', value: `${employeeDetails.value.total_working_hours} hours` },
    { label: 'Salary', value: `$${employeeDetails.value.salary}` },
    { label: 'Status', value: `${employeeDetails.value.status}` },
    { label: 'Paid Date', value: `${employeeDetails.value.paid_date || 'N/A'}` },
    { label: 'Position', value: `${employeeDetails.value.employee_position}` },
    { label: 'Department', value: `${employeeDetails.value.employee_department}` }
  ];

  details.forEach(detail => {
    doc.setFontSize(14);
    doc.text(`${detail.label}:`, marginLeft, yPosition);
    doc.setFont('helvetica', 'bold');
    doc.text(`${detail.value}`, marginLeft + 150, yPosition);
    
    yPosition += 25;
  });

  doc.setDrawColor(100);
  doc.line(marginLeft, doc.internal.pageSize.getHeight() - 60, doc.internal.pageSize.getWidth() - marginLeft, doc.internal.pageSize.getHeight() - 60);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by MIHRM Payroll System', doc.internal.pageSize.getWidth() / 2, doc.internal.pageSize.getHeight() - 40, { align: 'center' });

  doc.save(`Salary_Slip_${selectedMonth.value}.pdf`);
};

</script>

<style scoped>
/* Container and layout */
.salary-slip-container {
  max-width: 700px;
  margin: 40px auto;
  padding: 40px;
  background-color: #f7f8fc;
  border-radius: 12px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  font-family: 'Roboto', sans-serif;
}

/* Header styles */
.header h1 {
  text-align: center;
  font-size: 32px;
  color: #2a2a2a;
  margin-bottom: 30px;
  font-weight: 700;
}

/* Form group layout */
.form-group {
  margin-bottom: 25px;
}

label {
  font-size: 16px;
  color: #444;
  margin-bottom: 8px;
  display: block;
  font-weight: 500;
}

input[type="month"] {
  width: 100%;
  padding: 12px;
  font-size: 16px;
  border: 2px solid #ddd;
  border-radius: 8px;
  transition: border-color 0.3s ease;
}

input[type="month"]:focus {
  border-color: #4B49AC;
  outline: none;
}

/* Button styles */
.btn-fetch-salary,
.btn-download {
  width: 100%;
  padding: 14px;
  background-color: #4b49ac;
  color: white;
  border: none;
  border-radius: 8px;
  font-size: 18px;
  cursor: pointer;
  font-weight: 600;
  transition: background-color 0.3s ease;
  margin-top: 15px;
}

.btn-fetch-salary:hover,
.btn-download:hover {
  background-color: #3a3793;
}

.btn-fetch-salary:disabled {
  background-color: #b1b1d6;
  cursor: not-allowed;
}

/* Salary slip preview section */
.salary-slip-preview {
  margin-top: 30px;
  background-color: #fff;
  padding: 25px;
  border: 1px solid #e0e0e0;
  border-radius: 10px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
}

.salary-slip-preview h2 {
  font-size: 24px;
  margin-bottom: 20px;
  color: #333;
  font-weight: 600;
  text-align: center;
}

.slip-details p {
  font-size: 18px;
  margin-bottom: 15px;
  color: #333;
  display: flex;
  justify-content: space-between;
}

.slip-details strong {
  color: #555;
}
</style>
