<template>
    <div class="containerr d-flex justify-content-center align-items-center vh-100">
        <div class="row">
            <div class="col-6">
                <div class="card p-4 text-center" style="max-width: 400px; width: 100%;">
        <!-- Header -->
        <h3 class="mb-3">Set Up Authenticator</h3>
        <p class="text-muted">
          Scan the QR code with your authenticator app to set up two-factor authentication.
        </p>
  
        <!-- QR Code Placeholder -->
        <div class="qr-code-placeholder mb-4">
          <img
            :src="qrCode"
            alt="QR Code"
            class="img-fluid"
            style="max-width: 200px; margin: 0 auto;"
          />
        </div>
  
        <!-- Instructions -->
        <p class="text-muted">
          After scanning, enter the 6-digit code generated by your app.
        </p>
  
        <!-- Input for 6-Digit Code -->
        <form @submit.prevent="submitCode">
  
          <!-- Submit Button -->
          <div class="d-grid">
            <router-link to="./TwoFa">
                <button type="submit" class="btn btn-primary">
                  Verify
                </button>
            </router-link>
          </div>
        </form>
      </div>
            </div>
            <div class="col-6">
                <div class="container qr-img">
                    <img src="../assets/images/Qr.gif" alt="">
                </div>
            </div>
        </div>
    </div>
  </template>
  
  <script>
  import { ref } from 'vue';
  
  export default {
    setup() {
      const qrCode = ref('https://via.placeholder.com/200x200.png?text=QR+Code'); // Placeholder QR Code
      const authCode = ref('');
  
      // Function to handle the submission of the 6-digit code
      const submitCode = () => {
        if (authCode.value.length === 6) {
          console.log('2FA code submitted:', authCode.value);
          // Add logic to verify the code with the backend
        } else {
          console.log('Invalid code length');
        }
      };
  
      return {
        qrCode,
        authCode,
        submitCode,
      };
    },
  };
  </script>
  
  <style scoped>
  .containerr {
    background-color: #f8f9fa;

  }
  .row{
    margin-left: 175px;
  }
  .qr-img img{
    width: 400px;
  }
  .card {
    background-color: white;
    border-radius: 10px;
  }
  
  .qr-code-placeholder img {
    display: block;
  }
  
  .form-label {
    font-weight: 500;
  }
  </style>
  